import "./globals.scss";
import HomePage from "./page";

export const metadata = {
  title: 'A.H. Mardani',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="w-screen h-screen">
      <body>
        <HomePage>
          {children}
        </HomePage>
      </body>
    </html>
  )
}
