import "./globals.scss";

export const metadata = {
  title: 'A.H. Mardani',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="w-screen h-screen">
      <body>{children}</body>
    </html>
  )
}
